"""Compute branch disposition deterministically.

The facts (unique patches, lines a merge would delete, open-PR status) are
mechanical, so they are COMPUTED, never inferred. A language model classifying
these produced 36 MERGE verdicts including February branches that would delete
thousands of lines from main -- following it would have wrecked the repo.

Rules, applied in order. Each is stated so a human can audit the verdict:
  KEEP        - main, the active lane, or a bot-managed branch
  ARCHIVE     - has unique patches AND is net-additive AND is large
  CHERRY-PICK - has unique patches but merging would remove main content
  DELETE      - no unique patches AND no open PR
  REVIEW      - anything the rules cannot decide; a human looks at it

Deliberately conservative: REVIEW is the default, not DELETE. GPT's rule is that
a branch is never deleted for being old -- only for having no unique patch and
no open PR.
"""
import json
import subprocess
import sys

REPO = "C:/Users/SCM/Documents/GitHub/SCMessenger"
ACTIVE_LANE = "origin/fix/parity-critical-core"


def sh(args):
    try:
        return subprocess.run(
            args, cwd=REPO, capture_output=True, text=True, timeout=120
        ).stdout.strip()
    except Exception:
        return ""


def branches():
    out = sh(["git", "for-each-ref", "--format=%(refname:short)", "refs/remotes/origin"])
    return [b for b in out.splitlines() if b and b != "origin" and b != "origin/HEAD"]


def open_prs():
    out = sh(["gh", "pr", "list", "--state", "open", "--json", "number,headRefName", "-q",
              ".[] | .headRefName + \":\" + (.number|tostring)"])
    m = {}
    for line in out.splitlines():
        if ":" in line:
            ref, num = line.rsplit(":", 1)
            m["origin/" + ref] = num
    return m


def main():
    prs = open_prs()
    rows = []
    for b in branches():
        # Commits on b whose PATCH is not already applied on main.
        # --cherry-pick is essential: main was squash-merged, so ancestry lies.
        uniq = sh(["git", "log", "--cherry-pick", "--right-only", "--no-merges",
                   "--format=%h", "origin/main...%s" % b])
        uniq_n = len([x for x in uniq.splitlines() if x])

        # Lines a merge would ADD/REMOVE from main, code only.
        stat = sh(["git", "diff", "--numstat", "origin/main...%s" % b,
                   "--", ":!HANDOFF", ":!docs", ":!*.md"])
        add = rem = 0
        for line in stat.splitlines():
            p = line.split("\t")
            if len(p) >= 2 and p[0].isdigit() and p[1].isdigit():
                add += int(p[0])
                rem += int(p[1])

        last = sh(["git", "log", "-1", "--format=%cs", b])
        pr = prs.get(b, "")

        # --- deterministic classification ---
        if b in ("origin/main", ACTIVE_LANE):
            d, why = "KEEP", "canonical branch or active lane"
        elif "dependabot" in b:
            d, why = "KEEP", "bot-managed"
        elif uniq_n == 0 and not pr:
            d, why = "DELETE", "no unique patches (--cherry-pick) and no open PR"
        elif uniq_n == 0 and pr:
            d, why = "KEEP", "no unique patches but PR #%s is open" % pr
        elif rem > add and rem > 500:
            d, why = "CHERRY-PICK", (
                "has %d unique patches but merging would REMOVE %d lines from main"
                % (uniq_n, rem))
        elif rem == 0 and add > 10000:
            d, why = "ARCHIVE", "net-additive %d lines, preserve as tag not merge" % add
        else:
            d, why = "REVIEW", (
                "%d unique patches, +%d/-%d -- needs a human read" % (uniq_n, add, rem))

        rows.append(dict(branch=b, unique_patches=uniq_n, would_add=add,
                         would_remove=rem, open_pr=pr or None, last_commit=last,
                         disposition=d, reason=why))

    order = {"KEEP": 0, "REVIEW": 1, "CHERRY-PICK": 2, "ARCHIVE": 3, "DELETE": 4}
    rows.sort(key=lambda r: (order.get(r["disposition"], 9), r["last_commit"]), reverse=False)

    with open(REPO + "/docs/branch_disposition.json", "w", encoding="utf-8", newline="") as f:
        json.dump(rows, f, indent=2)
        f.write("\n")

    counts = {}
    for r in rows:
        counts[r["disposition"]] = counts.get(r["disposition"], 0) + 1

    with open(REPO + "/docs/BRANCH_DISPOSITION.md", "w", encoding="utf-8", newline="") as f:
        f.write("# Branch disposition table\n\n")
        f.write("Status: Active\nLast updated: 2026-08-03\n\n")
        f.write("Generated by `scripts/branch_disposition.py`. Every field is COMPUTED,\n")
        f.write("not inferred, and the classification rules are deterministic so any\n")
        f.write("verdict can be re-derived and audited.\n\n")
        f.write("## Why ancestry cannot be used\n\n")
        f.write("`main` is squash-merged, which creates a new commit and breaks ancestry.\n")
        f.write("`git merge-base --is-ancestor` therefore reports genuinely-merged work as\n")
        f.write("\"not on main\" -- the exact misreading that made PRs #118/#119 look\n")
        f.write("outstanding for a week when their content had already shipped.\n\n")
        f.write("`unique_patches` is `git log --cherry-pick --right-only --no-merges`,\n")
        f.write("which excludes commits whose PATCH is already applied on main regardless\n")
        f.write("of SHA. That is the only trustworthy signal here.\n\n")
        f.write("## Rules\n\n")
        f.write("| Disposition | Condition |\n|---|---|\n")
        f.write("| KEEP | canonical branch, active lane, or bot-managed |\n")
        f.write("| DELETE | zero unique patches AND no open PR |\n")
        f.write("| CHERRY-PICK | has unique patches, but merging would REMOVE >500 lines from main |\n")
        f.write("| ARCHIVE | net-additive and large -- preserve as a tag, do not merge |\n")
        f.write("| REVIEW | rules cannot decide; a human reads it |\n\n")
        f.write("A branch is NEVER classified DELETE for being old. Age is not a rule.\n")
        f.write("REVIEW is the default, so an unclear branch is examined rather than dropped.\n\n")
        f.write("## Summary\n\n")
        for k in ("KEEP", "REVIEW", "CHERRY-PICK", "ARCHIVE", "DELETE"):
            if k in counts:
                f.write("- %s: %d\n" % (k, counts[k]))
        f.write("\n## Table\n\n")
        f.write("| branch | uniq | +add | -rem | PR | last | disposition | reason |\n")
        f.write("|---|---|---|---|---|---|---|---|\n")
        for r in rows:
            f.write("| `%s` | %d | %d | %d | %s | %s | **%s** | %s |\n" % (
                r["branch"].replace("origin/", ""), r["unique_patches"],
                r["would_add"], r["would_remove"], r["open_pr"] or "-",
                r["last_commit"], r["disposition"], r["reason"]))

    print("branches:", len(rows))
    print("counts:", counts)


if __name__ == "__main__":
    main()
