#!/usr/bin/env bash
#
# Safe reclamation of Rust build artifacts.
#
# WHY THIS EXISTS -- the trap:
#
#   `cargo clean --target <triple>` DOES NOT scope to that triple.
#   It wipes ALL of target/.
#
# This has bitten this repo more than once: an invocation intended to reclaim
# ~4 GB deleted 44.7 GB. The flag reads like a filter and behaves like a
# sledgehammer. This script never calls `cargo clean` at all -- it removes
# specific directories by path, which is the only way to actually scope the
# operation.
#
# SECOND TRAP -- core/target/generated-sources/:
#
#   `scripts/ffi_surface.sh` silently depends on core/target/generated-sources/.
#   Note the path: it lives under core/target/, which is SEPARATE from the
#   workspace target/. A clean from the workspace root leaves it alone, but
#   `cargo clean` run from inside core/, or `cargo clean --target` (see trap 1),
#   destroys it. Losing it produces a VACUOUS "Updated Swift snapshot" with
#   exit 0 and no bindings -- a silent, passing lie.
#
#   This script backs it up before touching anything and verifies it afterward.
#
# Usage:
#   scripts/clean_target.sh --triples     remove cross-compile target dirs
#   scripts/clean_target.sh --deps        remove debug deps/build/incremental,
#                                         KEEPING built binaries
#   scripts/clean_target.sh --all         both of the above
#   scripts/clean_target.sh --dry-run     show what would go, delete nothing
#
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

DO_TRIPLES=0
DO_DEPS=0
DRY_RUN=0

for arg in "$@"; do
  case "$arg" in
    --triples) DO_TRIPLES=1 ;;
    --deps)    DO_DEPS=1 ;;
    --all)     DO_TRIPLES=1; DO_DEPS=1 ;;
    --dry-run) DRY_RUN=1 ;;
    *) echo "[ERROR] unknown argument: $arg"; exit 2 ;;
  esac
done

if [ "$DO_TRIPLES" -eq 0 ] && [ "$DO_DEPS" -eq 0 ]; then
  sed -n '2,30p' "$0" | sed 's/^# \{0,1\}//'
  exit 2
fi

free_gb() {
  df -k . 2>/dev/null | awk 'NR==2 {printf "%.1f", $4/1048576}'
}

# --- Guard: never clean while a build tool is running -------------------------
# Multiple agent sessions share this repo. Deleting object files out from under
# a live cargo/gradle invocation corrupts the build in ways that look like
# source errors.
if command -v tasklist >/dev/null 2>&1; then
  RUNNING=$(tasklist 2>/dev/null | grep -icE "cargo\.exe|rustc\.exe|gradle|java\.exe" || true)
else
  RUNNING=$(pgrep -c -f "cargo|rustc|gradle" 2>/dev/null || true)
fi
if [ "${RUNNING:-0}" -gt 0 ]; then
  echo "[ERROR] a build tool appears to be running (${RUNNING} process(es))."
  echo "[ERROR] refusing to delete build artifacts underneath it."
  echo "[INFO]  wait for it to finish, or stop it, then re-run."
  exit 1
fi

BEFORE=$(free_gb)
echo "[INFO] free before: ${BEFORE} GB"

# --- Insurance: back up generated-sources (about 1.2 MB) ----------------------
GS="core/target/generated-sources"
BACKUP=""
if [ -d "$GS" ]; then
  BACKUP="$(mktemp -d)/generated-sources"
  mkdir -p "$(dirname "$BACKUP")"
  cp -r "$GS" "$BACKUP"
  echo "[OK] backed up $GS -> $BACKUP"
else
  echo "[WARNING] $GS does not exist; nothing to preserve"
fi

remove() {
  local path="$1"
  [ -e "$path" ] || return 0
  local size
  size=$(du -sh "$path" 2>/dev/null | cut -f1)
  if [ "$DRY_RUN" -eq 1 ]; then
    echo "[DRY-RUN] would remove $path (${size})"
  else
    echo "[INFO] removing $path (${size})"
    rm -rf "$path"
  fi
}

if [ "$DO_TRIPLES" -eq 1 ]; then
  # Cross-compilation outputs. Regenerated by cargo-ndk / wasm builds, and CI
  # builds the shipping artifacts anyway.
  for d in target/*/; do
    name="$(basename "$d")"
    case "$name" in
      debug|release|tmp|CACHEDIR.TAG) continue ;;
    esac
    # Only triple-shaped directories (contain a '-'), never debug/release.
    case "$name" in
      *-*) remove "target/$name" ;;
    esac
  done
fi

if [ "$DO_DEPS" -eq 1 ]; then
  # Intermediate objects only. Built binaries in target/debug/ are KEPT so a
  # running node is not killed and does not need a rebuild to restart.
  remove "target/debug/deps"
  remove "target/debug/build"
  remove "target/debug/incremental"
  remove "target/debug/examples"
fi

# --- Verify the second trap did not fire -------------------------------------
if [ -n "$BACKUP" ]; then
  if [ -d "$GS" ] && [ -n "$(ls -A "$GS" 2>/dev/null)" ]; then
    echo "[OK] $GS intact"
  else
    echo "[WARNING] $GS was destroyed; restoring from backup"
    mkdir -p "$(dirname "$GS")"
    cp -r "$BACKUP" "$GS"
    echo "[OK] restored. Verify before running scripts/ffi_surface.sh --update"
  fi
fi

AFTER=$(free_gb)
echo "[INFO] free after:  ${AFTER} GB"
awk -v b="$BEFORE" -v a="$AFTER" 'BEGIN { printf "[DONE] reclaimed %.1f GB\n", a-b }'
